### ISSUE TITLE
Problems at Scientifica font.

### ISSUE THREAD

**Issue by efe3535** [EzequielRamis/liga#1]
![image](https://user-images.githubusercontent.com/46342237/149378304-7b3f5930-7835-4390-bf5d-0617dbe11cb3.png)
Right one is Liga scientifica and left one is normal scientifica.

**Comment by EzequielRamis** [comment]
Hi! Could you git checkout at branch `issue-1` and build it again? I tested the font in some emulators and got the spacing glitch too.

**Comment by efe3535** [comment]
It works now, thanks! :-)
![image](https://user-images.githubusercontent.com/46342237/149571909-6d22e54b-2bcc-4df4-aeb6-427153ab4aa6.png)
