### ISSUE TITLE
✓ Font ligated Fontforge has a bad day... attempt # ✓

### ISSUE THREAD

**Issue by aaravrav** [EzequielRamis/liga#2]
I get the error `✓ Font ligated Fontforge has a bad day... attempt # ✓` each time I try to ligaturize a font. I am trying to ligaturize the `Overpass Mono` font on Arch Linux

**Comment by EzequielRamis** [comment]
Hey! I've tested the static font family from [here](https://fonts.google.com/specimen/Overpass+Mono) and it got ligated. It's rare the script executes this dummy infinite loop. Try this:

- Before building, execute `scripts/clean.sh`
- And then `fonts/Overpass\ Mono/build.sh`

**Comment by aaravrav** [comment]
@EzequielRamis Hi, I tried to do this procedure with  10 more fonts, including the ones already provided in the repository, this is how it looks like: 
![image](https://user-images.githubusercontent.com/37036762/158797071-ad5df26d-824e-475b-bf70-6bc2cbdc8876.png)
A directory with the name and prefix of font is made with no files.

**Comment by EzequielRamis** [comment]
@aarav2you when you're building, `.log` files named by its font file are generated at `./logs/`. Could you show me the content of one of these?

**Comment by aaravrav** [comment]
Ah thank you! Never knew they existed, they are complaining the module `fontforge` is not installed even though I did via my package manager, I will just install it from pip. Perhaps the program could show the traceback instead of the static constant message.
