### ISSUE TITLE
`=` become very small

### ISSUE THREAD

**Issue by jilen** [EzequielRamis/liga#3]
Before 
![Screenshot from 2022-08-02 09-58-11](https://user-images.githubusercontent.com/546573/182275626-1517aac4-ab52-472a-88ba-824abb5bed97.png)

After
![Screenshot from 2022-08-02 09-58-58](https://user-images.githubusercontent.com/546573/182275655-e4814c7a-8a66-413f-9446-a6265f037278.png)

Patched font  https://www.dafont.com/code-saver.font

**Comment by EzequielRamis** [comment]
Hi! Could you try commenting [this line](https://github.com/EzequielRamis/liga/blob/main/config_sample.py#L31) in your config and building it again?

**Comment by jilen** [comment]
It works. Thanks.
